name: build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '26.1'
          - '27.1'
          - 'snapshot'
    name: Test on Emacs ${{ matrix.emacs_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: '26.3'
      - name: Install Cask
        uses: conao3/setup-cask@master
        with:
          version: 'snapshot'
      - name: Install Package and its Dependencies
        run: make install
      - name: Lint
        continue-on-error: true
        run: make lint
      - name: Check Docstrings
        continue-on-error: true
        run: make checkdoc
      - name: Byte Compile
        run: make build
      - name: Run Tests
        run: make test
